<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7eec1049463bf8c818d09a1ad71e3b00
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PostgreSQLTutorial\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PostgreSQLTutorial\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PostgreSQLTutorial\\Connection' => __DIR__ . '/../..' . '/classes/Connection.php',
        'PostgreSQLTutorial\\StoreProc' => __DIR__ . '/../..' . '/classes/StoreProc.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7eec1049463bf8c818d09a1ad71e3b00::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7eec1049463bf8c818d09a1ad71e3b00::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7eec1049463bf8c818d09a1ad71e3b00::$classMap;

        }, null, ClassLoader::class);
    }
}
