<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'PostgreSQLTutorial\\Connection' => $baseDir . '/classes/Connection.php',
    'PostgreSQLTutorial\\StoreProc' => $baseDir . '/classes/StoreProc.php',
);
